---
# Deploy Rocket.Chat on Docker
# https://docs.rocket.chat/docs/deploy-with-docker-docker-compose

- name: Create directory
  ansible.builtin.file:
    path: "{{ conf_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Template docker compose
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ conf_dir }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'
  become: true
  loop:
  - compose.yml
  - .env