---
# Deploy Rocket.Chat on Docker
# https://docs.rocket.chat/docs/deploy-with-docker-docker-compose

- name: Create directory
  ansible.builtin.file:
    path: "{{ conf_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Template docker compose
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ conf_dir }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'
  become: true
  loop:
  - compose.yml
  - .env

# Todo: Use set_fact for $env_template based on if admin is set!

# - name: Template .env
#   ansible.builtin.template:
#     src: "{{ env_template }}.j2"
#     dest: "{{ conf_dir }}/.env"
#     owner: "{{ ansible_env.USER }}"
#     group: "{{ ansible_env.USER }}"
#     mode: '0644'
#   become: true


- name: Firewall
  ansible.builtin.include_tasks:
    file: Firewall/main.yml

- name: devel helper
  ansible.builtin.include_tasks:
    file: .dev/main.yml
  when: devel