---
- name: Install dev tools
  ansible.builtin.dnf:
    name:
      - nano
    state: latest
  become: true

- name: History
  ansible.builtin.lineinfile:
    path: /root/.bash_history
    regexp: '^{{ item }}'
    line: "{{ item }}"
  become: true
  loop:
  - "cd {{ conf_dir }}"
  - "cat .env"
  - "docker compose up -d"
  - "docker compose logs -f rocketchat"

- name: Docker compose pull
  ansible.builtin.shell: docker compose pull
  args:
    chdir: "{{ conf_dir }}"